package net.minecraft.datafixer.fix;

import com.google.common.collect.Sets;
import com.mojang.datafixers.*;
import com.mojang.datafixers.schemas.Schema;
import com.mojang.datafixers.types.Type;
import com.mojang.datafixers.util.Pair;
import com.mojang.serialization.Dynamic;
import net.minecraft.datafixer.TypeReferences;
import net.minecraft.datafixer.schema.IdentifierNormalizingSchema;
import org.jspecify.annotations.Nullable;

import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Исправляет данные в формате DataFixer.
 */
public class ItemInstanceTheFlatteningFix extends DataFix {

	private static final Map<String, String> FLATTENING_MAP = Map.ofEntries(
		Map.entry("minecraft:stone.0", "minecraft:stone"),
		Map.entry("minecraft:stone.1", "minecraft:granite"),
		Map.entry("minecraft:stone.2", "minecraft:polished_granite"),
		Map.entry("minecraft:stone.3", "minecraft:diorite"),
		Map.entry("minecraft:stone.4", "minecraft:polished_diorite"),
		Map.entry("minecraft:stone.5", "minecraft:andesite"),
		Map.entry("minecraft:stone.6", "minecraft:polished_andesite"),
		Map.entry("minecraft:dirt.0", "minecraft:dirt"),
		Map.entry("minecraft:dirt.1", "minecraft:coarse_dirt"),
		Map.entry("minecraft:dirt.2", "minecraft:podzol"),
		Map.entry("minecraft:leaves.0", "minecraft:oak_leaves"),
		Map.entry("minecraft:leaves.1", "minecraft:spruce_leaves"),
		Map.entry("minecraft:leaves.2", "minecraft:birch_leaves"),
		Map.entry("minecraft:leaves.3", "minecraft:jungle_leaves"),
		Map.entry("minecraft:leaves2.0", "minecraft:acacia_leaves"),
		Map.entry("minecraft:leaves2.1", "minecraft:dark_oak_leaves"),
		Map.entry("minecraft:log.0", "minecraft:oak_log"),
		Map.entry("minecraft:log.1", "minecraft:spruce_log"),
		Map.entry("minecraft:log.2", "minecraft:birch_log"),
		Map.entry("minecraft:log.3", "minecraft:jungle_log"),
		Map.entry("minecraft:log2.0", "minecraft:acacia_log"),
		Map.entry("minecraft:log2.1", "minecraft:dark_oak_log"),
		Map.entry("minecraft:sapling.0", "minecraft:oak_sapling"),
		Map.entry("minecraft:sapling.1", "minecraft:spruce_sapling"),
		Map.entry("minecraft:sapling.2", "minecraft:birch_sapling"),
		Map.entry("minecraft:sapling.3", "minecraft:jungle_sapling"),
		Map.entry("minecraft:sapling.4", "minecraft:acacia_sapling"),
		Map.entry("minecraft:sapling.5", "minecraft:dark_oak_sapling"),
		Map.entry("minecraft:planks.0", "minecraft:oak_planks"),
		Map.entry("minecraft:planks.1", "minecraft:spruce_planks"),
		Map.entry("minecraft:planks.2", "minecraft:birch_planks"),
		Map.entry("minecraft:planks.3", "minecraft:jungle_planks"),
		Map.entry("minecraft:planks.4", "minecraft:acacia_planks"),
		Map.entry("minecraft:planks.5", "minecraft:dark_oak_planks"),
		Map.entry("minecraft:sand.0", "minecraft:sand"),
		Map.entry("minecraft:sand.1", "minecraft:red_sand"),
		Map.entry("minecraft:quartz_block.0", "minecraft:quartz_block"),
		Map.entry("minecraft:quartz_block.1", "minecraft:chiseled_quartz_block"),
		Map.entry("minecraft:quartz_block.2", "minecraft:quartz_pillar"),
		Map.entry("minecraft:anvil.0", "minecraft:anvil"),
		Map.entry("minecraft:anvil.1", "minecraft:chipped_anvil"),
		Map.entry("minecraft:anvil.2", "minecraft:damaged_anvil"),
		Map.entry("minecraft:wool.0", "minecraft:white_wool"),
		Map.entry("minecraft:wool.1", "minecraft:orange_wool"),
		Map.entry("minecraft:wool.2", "minecraft:magenta_wool"),
		Map.entry("minecraft:wool.3", "minecraft:light_blue_wool"),
		Map.entry("minecraft:wool.4", "minecraft:yellow_wool"),
		Map.entry("minecraft:wool.5", "minecraft:lime_wool"),
		Map.entry("minecraft:wool.6", "minecraft:pink_wool"),
		Map.entry("minecraft:wool.7", "minecraft:gray_wool"),
		Map.entry("minecraft:wool.8", "minecraft:light_gray_wool"),
		Map.entry("minecraft:wool.9", "minecraft:cyan_wool"),
		Map.entry("minecraft:wool.10", "minecraft:purple_wool"),
		Map.entry("minecraft:wool.11", "minecraft:blue_wool"),
		Map.entry("minecraft:wool.12", "minecraft:brown_wool"),
		Map.entry("minecraft:wool.13", "minecraft:green_wool"),
		Map.entry("minecraft:wool.14", "minecraft:red_wool"),
		Map.entry("minecraft:wool.15", "minecraft:black_wool"),
		Map.entry("minecraft:carpet.0", "minecraft:white_carpet"),
		Map.entry("minecraft:carpet.1", "minecraft:orange_carpet"),
		Map.entry("minecraft:carpet.2", "minecraft:magenta_carpet"),
		Map.entry("minecraft:carpet.3", "minecraft:light_blue_carpet"),
		Map.entry("minecraft:carpet.4", "minecraft:yellow_carpet"),
		Map.entry("minecraft:carpet.5", "minecraft:lime_carpet"),
		Map.entry("minecraft:carpet.6", "minecraft:pink_carpet"),
		Map.entry("minecraft:carpet.7", "minecraft:gray_carpet"),
		Map.entry("minecraft:carpet.8", "minecraft:light_gray_carpet"),
		Map.entry("minecraft:carpet.9", "minecraft:cyan_carpet"),
		Map.entry("minecraft:carpet.10", "minecraft:purple_carpet"),
		Map.entry("minecraft:carpet.11", "minecraft:blue_carpet"),
		Map.entry("minecraft:carpet.12", "minecraft:brown_carpet"),
		Map.entry("minecraft:carpet.13", "minecraft:green_carpet"),
		Map.entry("minecraft:carpet.14", "minecraft:red_carpet"),
		Map.entry("minecraft:carpet.15", "minecraft:black_carpet"),
		Map.entry("minecraft:hardened_clay.0", "minecraft:terracotta"),
		Map.entry("minecraft:stained_hardened_clay.0", "minecraft:white_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.1", "minecraft:orange_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.2", "minecraft:magenta_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.3", "minecraft:light_blue_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.4", "minecraft:yellow_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.5", "minecraft:lime_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.6", "minecraft:pink_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.7", "minecraft:gray_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.8", "minecraft:light_gray_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.9", "minecraft:cyan_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.10", "minecraft:purple_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.11", "minecraft:blue_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.12", "minecraft:brown_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.13", "minecraft:green_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.14", "minecraft:red_terracotta"),
		Map.entry("minecraft:stained_hardened_clay.15", "minecraft:black_terracotta"),
		Map.entry("minecraft:silver_glazed_terracotta.0", "minecraft:light_gray_glazed_terracotta"),
		Map.entry("minecraft:stained_glass.0", "minecraft:white_stained_glass"),
		Map.entry("minecraft:stained_glass.1", "minecraft:orange_stained_glass"),
		Map.entry("minecraft:stained_glass.2", "minecraft:magenta_stained_glass"),
		Map.entry("minecraft:stained_glass.3", "minecraft:light_blue_stained_glass"),
		Map.entry("minecraft:stained_glass.4", "minecraft:yellow_stained_glass"),
		Map.entry("minecraft:stained_glass.5", "minecraft:lime_stained_glass"),
		Map.entry("minecraft:stained_glass.6", "minecraft:pink_stained_glass"),
		Map.entry("minecraft:stained_glass.7", "minecraft:gray_stained_glass"),
		Map.entry("minecraft:stained_glass.8", "minecraft:light_gray_stained_glass"),
		Map.entry("minecraft:stained_glass.9", "minecraft:cyan_stained_glass"),
		Map.entry("minecraft:stained_glass.10", "minecraft:purple_stained_glass"),
		Map.entry("minecraft:stained_glass.11", "minecraft:blue_stained_glass"),
		Map.entry("minecraft:stained_glass.12", "minecraft:brown_stained_glass"),
		Map.entry("minecraft:stained_glass.13", "minecraft:green_stained_glass"),
		Map.entry("minecraft:stained_glass.14", "minecraft:red_stained_glass"),
		Map.entry("minecraft:stained_glass.15", "minecraft:black_stained_glass"),
		Map.entry("minecraft:stained_glass_pane.0", "minecraft:white_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.1", "minecraft:orange_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.2", "minecraft:magenta_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.3", "minecraft:light_blue_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.4", "minecraft:yellow_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.5", "minecraft:lime_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.6", "minecraft:pink_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.7", "minecraft:gray_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.8", "minecraft:light_gray_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.9", "minecraft:cyan_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.10", "minecraft:purple_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.11", "minecraft:blue_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.12", "minecraft:brown_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.13", "minecraft:green_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.14", "minecraft:red_stained_glass_pane"),
		Map.entry("minecraft:stained_glass_pane.15", "minecraft:black_stained_glass_pane"),
		Map.entry("minecraft:prismarine.0", "minecraft:prismarine"),
		Map.entry("minecraft:prismarine.1", "minecraft:prismarine_bricks"),
		Map.entry("minecraft:prismarine.2", "minecraft:dark_prismarine"),
		Map.entry("minecraft:concrete.0", "minecraft:white_concrete"),
		Map.entry("minecraft:concrete.1", "minecraft:orange_concrete"),
		Map.entry("minecraft:concrete.2", "minecraft:magenta_concrete"),
		Map.entry("minecraft:concrete.3", "minecraft:light_blue_concrete"),
		Map.entry("minecraft:concrete.4", "minecraft:yellow_concrete"),
		Map.entry("minecraft:concrete.5", "minecraft:lime_concrete"),
		Map.entry("minecraft:concrete.6", "minecraft:pink_concrete"),
		Map.entry("minecraft:concrete.7", "minecraft:gray_concrete"),
		Map.entry("minecraft:concrete.8", "minecraft:light_gray_concrete"),
		Map.entry("minecraft:concrete.9", "minecraft:cyan_concrete"),
		Map.entry("minecraft:concrete.10", "minecraft:purple_concrete"),
		Map.entry("minecraft:concrete.11", "minecraft:blue_concrete"),
		Map.entry("minecraft:concrete.12", "minecraft:brown_concrete"),
		Map.entry("minecraft:concrete.13", "minecraft:green_concrete"),
		Map.entry("minecraft:concrete.14", "minecraft:red_concrete"),
		Map.entry("minecraft:concrete.15", "minecraft:black_concrete"),
		Map.entry("minecraft:concrete_powder.0", "minecraft:white_concrete_powder"),
		Map.entry("minecraft:concrete_powder.1", "minecraft:orange_concrete_powder"),
		Map.entry("minecraft:concrete_powder.2", "minecraft:magenta_concrete_powder"),
		Map.entry("minecraft:concrete_powder.3", "minecraft:light_blue_concrete_powder"),
		Map.entry("minecraft:concrete_powder.4", "minecraft:yellow_concrete_powder"),
		Map.entry("minecraft:concrete_powder.5", "minecraft:lime_concrete_powder"),
		Map.entry("minecraft:concrete_powder.6", "minecraft:pink_concrete_powder"),
		Map.entry("minecraft:concrete_powder.7", "minecraft:gray_concrete_powder"),
		Map.entry("minecraft:concrete_powder.8", "minecraft:light_gray_concrete_powder"),
		Map.entry("minecraft:concrete_powder.9", "minecraft:cyan_concrete_powder"),
		Map.entry("minecraft:concrete_powder.10", "minecraft:purple_concrete_powder"),
		Map.entry("minecraft:concrete_powder.11", "minecraft:blue_concrete_powder"),
		Map.entry("minecraft:concrete_powder.12", "minecraft:brown_concrete_powder"),
		Map.entry("minecraft:concrete_powder.13", "minecraft:green_concrete_powder"),
		Map.entry("minecraft:concrete_powder.14", "minecraft:red_concrete_powder"),
		Map.entry("minecraft:concrete_powder.15", "minecraft:black_concrete_powder"),
		Map.entry("minecraft:cobblestone_wall.0", "minecraft:cobblestone_wall"),
		Map.entry("minecraft:cobblestone_wall.1", "minecraft:mossy_cobblestone_wall"),
		Map.entry("minecraft:sandstone.0", "minecraft:sandstone"),
		Map.entry("minecraft:sandstone.1", "minecraft:chiseled_sandstone"),
		Map.entry("minecraft:sandstone.2", "minecraft:cut_sandstone"),
		Map.entry("minecraft:red_sandstone.0", "minecraft:red_sandstone"),
		Map.entry("minecraft:red_sandstone.1", "minecraft:chiseled_red_sandstone"),
		Map.entry("minecraft:red_sandstone.2", "minecraft:cut_red_sandstone"),
		Map.entry("minecraft:stonebrick.0", "minecraft:stone_bricks"),
		Map.entry("minecraft:stonebrick.1", "minecraft:mossy_stone_bricks"),
		Map.entry("minecraft:stonebrick.2", "minecraft:cracked_stone_bricks"),
		Map.entry("minecraft:stonebrick.3", "minecraft:chiseled_stone_bricks"),
		Map.entry("minecraft:monster_egg.0", "minecraft:infested_stone"),
		Map.entry("minecraft:monster_egg.1", "minecraft:infested_cobblestone"),
		Map.entry("minecraft:monster_egg.2", "minecraft:infested_stone_bricks"),
		Map.entry("minecraft:monster_egg.3", "minecraft:infested_mossy_stone_bricks"),
		Map.entry("minecraft:monster_egg.4", "minecraft:infested_cracked_stone_bricks"),
		Map.entry("minecraft:monster_egg.5", "minecraft:infested_chiseled_stone_bricks"),
		Map.entry("minecraft:yellow_flower.0", "minecraft:dandelion"),
		Map.entry("minecraft:red_flower.0", "minecraft:poppy"),
		Map.entry("minecraft:red_flower.1", "minecraft:blue_orchid"),
		Map.entry("minecraft:red_flower.2", "minecraft:allium"),
		Map.entry("minecraft:red_flower.3", "minecraft:azure_bluet"),
		Map.entry("minecraft:red_flower.4", "minecraft:red_tulip"),
		Map.entry("minecraft:red_flower.5", "minecraft:orange_tulip"),
		Map.entry("minecraft:red_flower.6", "minecraft:white_tulip"),
		Map.entry("minecraft:red_flower.7", "minecraft:pink_tulip"),
		Map.entry("minecraft:red_flower.8", "minecraft:oxeye_daisy"),
		Map.entry("minecraft:double_plant.0", "minecraft:sunflower"),
		Map.entry("minecraft:double_plant.1", "minecraft:lilac"),
		Map.entry("minecraft:double_plant.2", "minecraft:tall_grass"),
		Map.entry("minecraft:double_plant.3", "minecraft:large_fern"),
		Map.entry("minecraft:double_plant.4", "minecraft:rose_bush"),
		Map.entry("minecraft:double_plant.5", "minecraft:peony"),
		Map.entry("minecraft:deadbush.0", "minecraft:dead_bush"),
		Map.entry("minecraft:tallgrass.0", "minecraft:dead_bush"),
		Map.entry("minecraft:tallgrass.1", "minecraft:grass"),
		Map.entry("minecraft:tallgrass.2", "minecraft:fern"),
		Map.entry("minecraft:sponge.0", "minecraft:sponge"),
		Map.entry("minecraft:sponge.1", "minecraft:wet_sponge"),
		Map.entry("minecraft:purpur_slab.0", "minecraft:purpur_slab"),
		Map.entry("minecraft:stone_slab.0", "minecraft:stone_slab"),
		Map.entry("minecraft:stone_slab.1", "minecraft:sandstone_slab"),
		Map.entry("minecraft:stone_slab.2", "minecraft:petrified_oak_slab"),
		Map.entry("minecraft:stone_slab.3", "minecraft:cobblestone_slab"),
		Map.entry("minecraft:stone_slab.4", "minecraft:brick_slab"),
		Map.entry("minecraft:stone_slab.5", "minecraft:stone_brick_slab"),
		Map.entry("minecraft:stone_slab.6", "minecraft:nether_brick_slab"),
		Map.entry("minecraft:stone_slab.7", "minecraft:quartz_slab"),
		Map.entry("minecraft:stone_slab2.0", "minecraft:red_sandstone_slab"),
		Map.entry("minecraft:wooden_slab.0", "minecraft:oak_slab"),
		Map.entry("minecraft:wooden_slab.1", "minecraft:spruce_slab"),
		Map.entry("minecraft:wooden_slab.2", "minecraft:birch_slab"),
		Map.entry("minecraft:wooden_slab.3", "minecraft:jungle_slab"),
		Map.entry("minecraft:wooden_slab.4", "minecraft:acacia_slab"),
		Map.entry("minecraft:wooden_slab.5", "minecraft:dark_oak_slab"),
		Map.entry("minecraft:coal.0", "minecraft:coal"),
		Map.entry("minecraft:coal.1", "minecraft:charcoal"),
		Map.entry("minecraft:fish.0", "minecraft:cod"),
		Map.entry("minecraft:fish.1", "minecraft:salmon"),
		Map.entry("minecraft:fish.2", "minecraft:clownfish"),
		Map.entry("minecraft:fish.3", "minecraft:pufferfish"),
		Map.entry("minecraft:cooked_fish.0", "minecraft:cooked_cod"),
		Map.entry("minecraft:cooked_fish.1", "minecraft:cooked_salmon"),
		Map.entry("minecraft:skull.0", "minecraft:skeleton_skull"),
		Map.entry("minecraft:skull.1", "minecraft:wither_skeleton_skull"),
		Map.entry("minecraft:skull.2", "minecraft:zombie_head"),
		Map.entry("minecraft:skull.3", "minecraft:player_head"),
		Map.entry("minecraft:skull.4", "minecraft:creeper_head"),
		Map.entry("minecraft:skull.5", "minecraft:dragon_head"),
		Map.entry("minecraft:golden_apple.0", "minecraft:golden_apple"),
		Map.entry("minecraft:golden_apple.1", "minecraft:enchanted_golden_apple"),
		Map.entry("minecraft:fireworks.0", "minecraft:firework_rocket"),
		Map.entry("minecraft:firework_charge.0", "minecraft:firework_star"),
		Map.entry("minecraft:dye.0", "minecraft:ink_sac"),
		Map.entry("minecraft:dye.1", "minecraft:rose_red"),
		Map.entry("minecraft:dye.2", "minecraft:cactus_green"),
		Map.entry("minecraft:dye.3", "minecraft:cocoa_beans"),
		Map.entry("minecraft:dye.4", "minecraft:lapis_lazuli"),
		Map.entry("minecraft:dye.5", "minecraft:purple_dye"),
		Map.entry("minecraft:dye.6", "minecraft:cyan_dye"),
		Map.entry("minecraft:dye.7", "minecraft:light_gray_dye"),
		Map.entry("minecraft:dye.8", "minecraft:gray_dye"),
		Map.entry("minecraft:dye.9", "minecraft:pink_dye"),
		Map.entry("minecraft:dye.10", "minecraft:lime_dye"),
		Map.entry("minecraft:dye.11", "minecraft:dandelion_yellow"),
		Map.entry("minecraft:dye.12", "minecraft:light_blue_dye"),
		Map.entry("minecraft:dye.13", "minecraft:magenta_dye"),
		Map.entry("minecraft:dye.14", "minecraft:orange_dye"),
		Map.entry("minecraft:dye.15", "minecraft:bone_meal"),
		Map.entry("minecraft:silver_shulker_box.0", "minecraft:light_gray_shulker_box"),
		Map.entry("minecraft:fence.0", "minecraft:oak_fence"),
		Map.entry("minecraft:fence_gate.0", "minecraft:oak_fence_gate"),
		Map.entry("minecraft:wooden_door.0", "minecraft:oak_door"),
		Map.entry("minecraft:boat.0", "minecraft:oak_boat"),
		Map.entry("minecraft:lit_pumpkin.0", "minecraft:jack_o_lantern"),
		Map.entry("minecraft:pumpkin.0", "minecraft:carved_pumpkin"),
		Map.entry("minecraft:trapdoor.0", "minecraft:oak_trapdoor"),
		Map.entry("minecraft:nether_brick.0", "minecraft:nether_bricks"),
		Map.entry("minecraft:red_nether_brick.0", "minecraft:red_nether_bricks"),
		Map.entry("minecraft:netherbrick.0", "minecraft:nether_brick"),
		Map.entry("minecraft:wooden_button.0", "minecraft:oak_button"),
		Map.entry("minecraft:wooden_pressure_plate.0", "minecraft:oak_pressure_plate"),
		Map.entry("minecraft:noteblock.0", "minecraft:note_block"),
		Map.entry("minecraft:bed.0", "minecraft:white_bed"),
		Map.entry("minecraft:bed.1", "minecraft:orange_bed"),
		Map.entry("minecraft:bed.2", "minecraft:magenta_bed"),
		Map.entry("minecraft:bed.3", "minecraft:light_blue_bed"),
		Map.entry("minecraft:bed.4", "minecraft:yellow_bed"),
		Map.entry("minecraft:bed.5", "minecraft:lime_bed"),
		Map.entry("minecraft:bed.6", "minecraft:pink_bed"),
		Map.entry("minecraft:bed.7", "minecraft:gray_bed"),
		Map.entry("minecraft:bed.8", "minecraft:light_gray_bed"),
		Map.entry("minecraft:bed.9", "minecraft:cyan_bed"),
		Map.entry("minecraft:bed.10", "minecraft:purple_bed"),
		Map.entry("minecraft:bed.11", "minecraft:blue_bed"),
		Map.entry("minecraft:bed.12", "minecraft:brown_bed"),
		Map.entry("minecraft:bed.13", "minecraft:green_bed"),
		Map.entry("minecraft:bed.14", "minecraft:red_bed"),
		Map.entry("minecraft:bed.15", "minecraft:black_bed"),
		Map.entry("minecraft:banner.15", "minecraft:white_banner"),
		Map.entry("minecraft:banner.14", "minecraft:orange_banner"),
		Map.entry("minecraft:banner.13", "minecraft:magenta_banner"),
		Map.entry("minecraft:banner.12", "minecraft:light_blue_banner"),
		Map.entry("minecraft:banner.11", "minecraft:yellow_banner"),
		Map.entry("minecraft:banner.10", "minecraft:lime_banner"),
		Map.entry("minecraft:banner.9", "minecraft:pink_banner"),
		Map.entry("minecraft:banner.8", "minecraft:gray_banner"),
		Map.entry("minecraft:banner.7", "minecraft:light_gray_banner"),
		Map.entry("minecraft:banner.6", "minecraft:cyan_banner"),
		Map.entry("minecraft:banner.5", "minecraft:purple_banner"),
		Map.entry("minecraft:banner.4", "minecraft:blue_banner"),
		Map.entry("minecraft:banner.3", "minecraft:brown_banner"),
		Map.entry("minecraft:banner.2", "minecraft:green_banner"),
		Map.entry("minecraft:banner.1", "minecraft:red_banner"),
		Map.entry("minecraft:banner.0", "minecraft:black_banner"),
		Map.entry("minecraft:grass.0", "minecraft:grass_block"),
		Map.entry("minecraft:brick_block.0", "minecraft:bricks"),
		Map.entry("minecraft:end_bricks.0", "minecraft:end_stone_bricks"),
		Map.entry("minecraft:golden_rail.0", "minecraft:powered_rail"),
		Map.entry("minecraft:magma.0", "minecraft:magma_block"),
		Map.entry("minecraft:quartz_ore.0", "minecraft:nether_quartz_ore"),
		Map.entry("minecraft:reeds.0", "minecraft:sugar_cane"),
		Map.entry("minecraft:slime.0", "minecraft:slime_block"),
		Map.entry("minecraft:stone_stairs.0", "minecraft:cobblestone_stairs"),
		Map.entry("minecraft:waterlily.0", "minecraft:lily_pad"),
		Map.entry("minecraft:web.0", "minecraft:cobweb"),
		Map.entry("minecraft:snow.0", "minecraft:snow_block"),
		Map.entry("minecraft:snow_layer.0", "minecraft:snow"),
		Map.entry("minecraft:record_11.0", "minecraft:music_disc_11"),
		Map.entry("minecraft:record_13.0", "minecraft:music_disc_13"),
		Map.entry("minecraft:record_blocks.0", "minecraft:music_disc_blocks"),
		Map.entry("minecraft:record_cat.0", "minecraft:music_disc_cat"),
		Map.entry("minecraft:record_chirp.0", "minecraft:music_disc_chirp"),
		Map.entry("minecraft:record_far.0", "minecraft:music_disc_far"),
		Map.entry("minecraft:record_mall.0", "minecraft:music_disc_mall"),
		Map.entry("minecraft:record_mellohi.0", "minecraft:music_disc_mellohi"),
		Map.entry("minecraft:record_stal.0", "minecraft:music_disc_stal"),
		Map.entry("minecraft:record_strad.0", "minecraft:music_disc_strad"),
		Map.entry("minecraft:record_wait.0", "minecraft:music_disc_wait"),
		Map.entry("minecraft:record_ward.0", "minecraft:music_disc_ward")
	);
	private static final Set<String> ORIGINAL_ITEM_NAMES = FLATTENING_MAP.keySet()
	                                                                     .stream()
	                                                                     .map(oldId -> oldId.substring(
			                                                                     0,
			                                                                     oldId.indexOf(46)
	                                                                     ))
	                                                                     .collect(Collectors.toSet());
	private static final Set<String> DAMAGEABLE_ITEMS = Sets.newHashSet(
			new String[]{
					"minecraft:bow",
					"minecraft:carrot_on_a_stick",
					"minecraft:chainmail_boots",
					"minecraft:chainmail_chestplate",
					"minecraft:chainmail_helmet",
					"minecraft:chainmail_leggings",
					"minecraft:diamond_axe",
					"minecraft:diamond_boots",
					"minecraft:diamond_chestplate",
					"minecraft:diamond_helmet",
					"minecraft:diamond_hoe",
					"minecraft:diamond_leggings",
					"minecraft:diamond_pickaxe",
					"minecraft:diamond_shovel",
					"minecraft:diamond_sword",
					"minecraft:elytra",
					"minecraft:fishing_rod",
					"minecraft:flint_and_steel",
					"minecraft:golden_axe",
					"minecraft:golden_boots",
					"minecraft:golden_chestplate",
					"minecraft:golden_helmet",
					"minecraft:golden_hoe",
					"minecraft:golden_leggings",
					"minecraft:golden_pickaxe",
					"minecraft:golden_shovel",
					"minecraft:golden_sword",
					"minecraft:iron_axe",
					"minecraft:iron_boots",
					"minecraft:iron_chestplate",
					"minecraft:iron_helmet",
					"minecraft:iron_hoe",
					"minecraft:iron_leggings",
					"minecraft:iron_pickaxe",
					"minecraft:iron_shovel",
					"minecraft:iron_sword",
					"minecraft:leather_boots",
					"minecraft:leather_chestplate",
					"minecraft:leather_helmet",
					"minecraft:leather_leggings",
					"minecraft:shears",
					"minecraft:shield",
					"minecraft:stone_axe",
					"minecraft:stone_hoe",
					"minecraft:stone_pickaxe",
					"minecraft:stone_shovel",
					"minecraft:stone_sword",
					"minecraft:wooden_axe",
					"minecraft:wooden_hoe",
					"minecraft:wooden_pickaxe",
					"minecraft:wooden_shovel",
					"minecraft:wooden_sword"
			}
	);

	public ItemInstanceTheFlatteningFix(Schema schema, boolean bl) {
		super(schema, bl);
	}

	public TypeRewriteRule makeRule() {
		Type<?> type = getInputSchema().getType(TypeReferences.ITEM_STACK);
		OpticFinder<Pair<String, String>> opticFinder = DSL.fieldFinder(
				"id", DSL.named(TypeReferences.ITEM_NAME.typeName(), IdentifierNormalizingSchema.getIdentifierType())
		);
		OpticFinder<?> opticFinder2 = type.findField("tag");
		return fixTypeEverywhereTyped(
				"ItemInstanceTheFlatteningFix", type, itemStackTyped -> {
					Optional<Pair<String, String>> optional = itemStackTyped.getOptional(opticFinder);
					if (optional.isEmpty()) {
						return itemStackTyped;
					}
					else {
						Typed<?> typed = itemStackTyped;
						Dynamic<?> dynamic = (Dynamic<?>) itemStackTyped.get(DSL.remainderFinder());
						int i = dynamic.get("Damage").asInt(0);
						String string = getItem((String) optional.get().getSecond(), i);
						if (string != null) {
							typed =
									itemStackTyped.set(
											opticFinder,
											Pair.of(TypeReferences.ITEM_NAME.typeName(), string)
									);
						}

						if (DAMAGEABLE_ITEMS.contains(optional.get().getSecond())) {
							Typed<?> typed2 = itemStackTyped.getOrCreateTyped(opticFinder2);
							Dynamic<?> dynamic2 = (Dynamic<?>) typed2.get(DSL.remainderFinder());
							dynamic2 = dynamic2.set("Damage", dynamic2.createInt(i));
							typed = typed.set(opticFinder2, typed2.set(DSL.remainderFinder(), dynamic2));
						}

						return typed.set(DSL.remainderFinder(), dynamic.remove("Damage"));
					}
				}
		);
	}

	public static @Nullable String getItem(@Nullable String originalName, int damage) {
		if (ORIGINAL_ITEM_NAMES.contains(originalName)) {
			String string = FLATTENING_MAP.get(originalName + "." + damage);
			return string == null ? FLATTENING_MAP.get(originalName + ".0") : string;
		}
		else {
			return null;
		}
	}
}
